asanaTask:
  name: name
  notes: description
  dueDate: date1
  assignee: assignedTo

jama_url: ENTER_JAMA_URL_HERE
jama_username: ENTER_JAMA_USER_HERE
jama_password: ENTER_JAMA_PASSWORD_HERE

asanaApiKey: ENTER_KEY_HERE
asanaProjectId: 22747227023403
jamaProjectId: 24114
jamaTaskItemTypeId: 107368
jamaTaskSetId: 2736824

server:
  port: 8881