asanaTask:
  name: name
  notes: description
  dueDate: date1

jama:
  url: http://localhost:8080/contour
  username: jgoetz
  password: password

asanaApiKey: 77H6ILO3.8RMTGiDJECdEpVpF3ZcMSb8
asanaProjectId: 25088409559155
jamaProjectId: 24114
jamaTaskItemTypeId: 107368
jamaTaskSetId: 2736824

server:
  port: 8881