asanaTask:
  name: name
  notes: description
  dueDate: date1
  assignee: assignedTo

jama_url: http://localhost:8080/contour
jama_username: sample
jama_password: password

asanaApiKey: 4mTQwPq1.0HrwyVy06HRN7qilbu6RXW2
asanaProjectId: 15387227838023
jamaProjectId: 1
jamaTaskItemTypeId: 23
jamaTaskSetId: 236

server:
  port: 8881