asanaTask:
  name: name
  notes: description

jama:
  url: http://localhost:8080/contour
  username: sample
  password: password

asanaApiKey: 4mTQwPq1.0HrwyVy06HRN7qilbu6RXW2
asanaProjectId: 15387227838023
jamaProjectId: 2

server:
  port: 8881